### ISSUE TITLE
Base theme not changing.

### ISSUE THREAD

**Issue by tommyent** [joaomgcd/JoinChrome#108]
Base theme not changing on change. It will if you refresh the page.

options.js:321 Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at Object.setTheme (chrome-extension://flejfacjooompmliegamfbpjjdlhokhj/js/base/utilsdom.js:247:56)
    at Object.setGeneratedColors (chrome-extension://flejfacjooompmliegamfbpjjdlhokhj/js/base/utilsdom.js:135:12)
    at Object.setTheme (chrome-extension://flejfacjooompmliegamfbpjjdlhokhj/js/base/utilsdom.js:149:13)
    at DevicesEventHandler.onThemeChanged (chrome-extension://flejfacjooompmliegamfbpjjdlhokhj/devices.js:322:12)
    at sendToRegistered (chrome-extension://flejfacjooompmliegamfbpjjdlhokhj/js/base/eventBus.js:61:9)
    at EventBus.me.post (chrome-extension://flejfacjooompmliegamfbpjjdlhokhj/js/base/eventBus.js:68:7)
    at HTMLSelectElement.document.getElementById.onchange (chrome-extension://flejfacjooompmliegamfbpjjdlhokhj/options.js:321:72)

**Comment by joaomgcd** [comment]
Hi. Sorry for the delay. It's still changing for me as soon as I change the option in the dropdown. What Chrome version are you using?

**Comment by tommyent** [comment]
Hi @joaomgcd, 
Hope you're doing well. My laptop died in between then and now but everything is working on the new one so I will close this. Thanks for getting back to me.

**Comment by joaomgcd** [comment]
Great to know that it's working. Thanks!
